name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    # এটি গিটহাবের ক্যাশ করা অফিশিয়াল রানার ব্যবহার করবে, আলাদা কোনো নেটওয়ার্ক ডাউনলোড ছাড়াই
    - name: Install Playwright Browsers
      uses: microsoft/playwright-github-action@v1
    - name: Run Playwright tests
      run: npx playwright test
